<?php
/**
 * @var AbstractProduct $block
 * @var Escaper $escaper
 */

use Magento\Catalog\Block\Product\AbstractProduct;
use Magento\Framework\Escaper;

$blockType = $block->getType();

if ($blockType === 'related'): ?>
    <div class="related-products-container">
        <div class="related-products-title">
            <h3><?= __('Related products') ?></h3>
        </div>
        <div class="related-items-list">
            <?php foreach ($block->getItems() as $_item): ?>
                <div class="product-item">
                    <div class="product-item-image">
                        <?= $block->getImage($_item, 'category_page_grid')->toHtml() ?>
                    </div>
                    <div class="product-item-details">
                        <strong class="product-item-name"><?= $escaper->escapeHtml($_item->getName()) ?></strong>
                        <div class="product-item-review">
                            <?= $block->getReviewsSummaryHtml($_item, "short", true) ?>
                        </div>
                        <div class="product-item-price">
                            <?= $block->getProductPrice($_item) ?>
                        </div>
                        <div class="product-item-cart">
                            <form action="<?= $escaper->escapeUrl($block->getAddToCartUrl($_item)) ?>" method="post">
                                <button type="submit" title="<?= $escaper->escapeHtmlAttr(__('Add to Cart')) ?>"
                                        class="action tocart primary">
                                    <span><?= $escaper->escapeHtml(__('Add to Cart')) ?></span>
                                </button>
                            </form>
                        </div>
                    </div>
                </div>
            <?php endforeach; ?>
        </div>
    </div>
<?php endif; ?>

<?php if ($blockType === 'upsell'): ?>
    <div class="upsell-products">
        <div class="title-container">
            <h4 class="upsell-title"><?= __('We found other products you might like!') ?></h4>
        </div>
        <div class="upsell-items-list">
            <?php foreach ($block->getItems() as $_item): ?>
                $reviewSummary = $block->getReviewsSummaryHtml($_item, "short", true);
                $price = $block->getProductPrice($_item);
                ?>

                <div class="upsell-product-item">
                    <div class="product-item-image">
                        <a href="<?= $escaper->escapeUrl($_item->getProductUrl()) ?>">
                            <?= $escaper->escapeHtml($block->getImage($_item, 'category_page_grid')->toHtml()); ?>
                        </a>
                    </div>
                    <div class="product-item-details">
                        <div>
                            <strong class="product-item-name"><?= $escaper->escapeHtml($_item->getName()) ?></strong>
                            <div class="product-item-review">
                                <?= $escaper->escapeHtml($block->getReviewsSummaryHtml($_item, "short", true)) ?>
                            </div>
                            <div class="product-item-price">
                                <?= $escaper->escapeHtml($block->getProductPrice($_item)) ?>
                            </div>
                        </div>
                        <div>
                            <div class="product-item-action">
                                <a href="<?= $escaper->escapeUrl($_item->getProductUrl()) ?>"
                                   class="action view-product">
                                    <?= $escaper->escapeHtml(__('View Product')) ?>
                                </a>
                            </div>
                        </div>
                    </div>
                </div>
            <?php endforeach; ?>
        </div>
    </div>
<?php endif; ?>
