version: "3.9"

name: magento

services:
  php:
    image: 369129824209.dkr.ecr.eu-west-1.amazonaws.com/magebit-docker:php-8.1-fpm
    volumes:
      - ./.:/var/www/html
      - sock_data:/sock
    environment:
      - COMPOSER_VERSION=2
    depends_on:
      - db
      - redis
      - opensearch

  xdebug:
    image: 369129824209.dkr.ecr.eu-west-1.amazonaws.com/magebit-docker:php-8.1-fpm-xdebug
    environment:
      - PHP_IDE_CONFIG=serverName=magento.docker
    volumes:
      - ./.:/var/www/html
      - sock_data:/sock
    depends_on:
      - db
      - redis
      - opensearch

  nginx:
    image: 369129824209.dkr.ecr.eu-west-1.amazonaws.com/magebit-docker:nginx-1.17
    volumes:
      - ./.:/var/www/html:ro
      - sock_data:/sock
    depends_on:
      - php
      - xdebug

  redis:
    image: redis:7.0-alpine
    volumes:
      - redis_data:/data
    networks:
      default:
        aliases:
          - redis.magento.docker

  opensearch:
    image: 369129824209.dkr.ecr.eu-west-1.amazonaws.com/magebit-docker:opensearch-2.5.0
    environment:
      - discovery.type=single-node
      - plugins.security.disabled=true
    volumes:
      - opensearch_data:/usr/share/opensearch/data
    networks:
      default:
        aliases:
          - es.magento.docker

  db:
    image: mariadb:10.6
    environment:
      - MYSQL_USER=magento
      - MYSQL_PASSWORD=magento
      - MYSQL_DATABASE=magento
      - MYSQL_ROOT_PASSWORD=magento
    volumes:
      - ./.docker/mysql/docker-entrypoint-initdb.d:/docker-entrypoint-initdb.d/
      - db_data:/var/lib/mysql
    networks:
      default:
        aliases:
          - db.magento.docker

volumes:
  sock_data:
  db_data:
  redis_data:
  opensearch_data:
