<?php
/**
 * @var View $block
 * @var Escaper $escaper
 */

use Magento\Catalog\Block\Product\View;
use Magento\Framework\App\ObjectManager;
use Magento\Framework\Escaper;

$product = $block->getProduct();

$objectManager = ObjectManager::getInstance();
$stockState = $objectManager->get('\Magento\InventorySalesApi\Api\GetProductSalableQtyInterface');
$qtyAvailable = $stockState->execute($product->getSku(), 2);
$isInStock = $qtyAvailable > 0;
?>
<div id="add-to-cart-container" class="add-to-cart-container" data-bind="scope:'qty-counter'">
    <!-- ko template: getTemplate() --><!-- /ko -->
    <script type="text/x-magento-init">
        {
            "#add-to-cart-container": {
                "Magento_Ui/js/core/app": {
                    "components": {
                        "qty-counter": {
                            "component": "Magento_Catalog/js/qty-counter",
                            "product_id": <?= /* @noEscape */ $block->getProduct()->getId() ?>
                        }
                    }
                }
            }
        }
    </script>
</div>
<?php if ($isInStock && $qtyAvailable > 0): ?>
    <div class="stock-availability">
        <img class="checkmark" src="<?= $escaper->escapeUrl($block->getViewFileUrl('images/check-mark-green.png')) ?>" alt="check-mark">
        <span class="in-stock"><?= __('IN STOCK') ?></span>
        <span class="items-available"><?= (int)$qtyAvailable . ' ' . __('items available') ?></span>
    </div>
<?php endif; ?>
<div class="actions">
    <button type="submit"
            class="action primary tocart"
            id="product-addtocart-button">
        <span><?= __('Add to Cart') ?></span>
    </button>
    <?php echo $escaper->escapeHtml($block->getChildHtml('', true)) ?>
</div>
