<?php
/**
 * @var View $block
 * @var Escaper $escaper
 */

use Magento\Catalog\Block\Product\View;
use Magento\Framework\Escaper;

$product = $block->getProduct();
$attributes = $product->getAttributes();

$mainAttributes = [];
$secondaryAttributes = [];

$mainCodes = ['color', 'material', 'dimensions'];

// Split attributes into 2 groups.
foreach ($attributes as $attribute) {
    if (in_array($attribute->getAttributeCode(), $mainCodes)) {
        $mainAttributes[] = $attribute;
    } else {
        $secondaryAttributes[] = $attribute;
    }
}

// Check if all main attributes could be filled out.
// If some are missing, then add from secondary attributes.
$countMain = count($mainAttributes);
$countRequired = count($mainCodes);
$diff = $countRequired - $countMain;

// Loop $diff times, to fill out the primary attributes to size 3.
for ($i = 0; $i < $diff; $i++) {
    $mainAttributes[] = $secondaryAttributes[$i];
}
?>

<div class="product-attributes-list">
    <ul>
        <?php foreach ($mainAttributes as $attribute): ?>
            <?php if ($attribute->getIsVisibleOnFront() && !is_null($product->getData($attribute->getAttributeCode()))): ?>
                <?php
                $label = $attribute->getStoreLabel();
                $value = $attribute->getFrontend()->getValue($product);
                ?>
                <?= '<li><strong>' . $escaper->escapeHtml($label) . ':</strong> ' . $escaper->escapeHtml($value) . '</li>' ?>;
                ?>
            <?php endif; ?>
        <?php endforeach; ?>
    </ul>
    <p>
        <?= $escaper->escapeHtml($product->getShortDescription()); ?>
    </p>
</div>
